/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_BLEServer */

#ifndef _Included_main_java_BLEServer
#define _Included_main_java_BLEServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_BLEServer
 * Method:    nativeStartServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_main_java_BLEServer_nativeStartServer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     main_java_BLEServer
 * Method:    nativeStopServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_BLEServer_nativeStopServer
  (JNIEnv *, jobject);

/*
 * Class:     main_java_BLEServer
 * Method:    nativeNotify
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_main_java_BLEServer_nativeNotify
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
